In [8]:
print ('Hello world')
print('Lets do it')

Hello world
Lets do it


In [9]:
import numpy as np
import pandas as pd
#numpy helps in the multidimensional array handling
#pands -> datafrome handling
#Matplotlib-> Visualization packages
#Scipy-> Statistical maodel

In [10]:
#addition
a = 5
b = 6
c = a + b
print('c value',c)
print('addition', a + b)

#subtraction
print("subtraction", a - b)

#multiplication
print('multiply', a * b)

#divide
print ('divide', a / b)

float_var = float(a)
print ('float value', float_var)

hex_val = hex(b)
print ('hex value', hex_val)

d = 56
oct_val = oct(d)
print ('oct_val' , oct_val)

c value 11
addition 11
subtraction -1
multiply 30
divide 0.8333333333333334
float value 5.0
hex value 0x6
oct_val 0o70


In [11]:
#Numpy creation of matrices and the vectors array
simple_list = [1, 2, 3, 4]
simple_list
np.array(simple_list)

array([1, 2, 3, 4])

In [12]:
#creation of the range values for the same
np.arange(0,45)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [13]:
#creation of the zeroes
np.zeros(31)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#creation of the ones
np.ones(24)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [15]:
#creation of the identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#range in the step size
np.arange(4,55,5)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54])

In [17]:
#genration of the random variables
np.random.rand(6)

array([0.28236218, 0.19460779, 0.97648022, 0.8916523 , 0.13663979,
       0.27866984])

In [18]:
np.random.rand(4,5)

array([[0.82979397, 0.88629321, 0.27071915, 0.76375288, 0.91179043],
       [0.75748142, 0.09650623, 0.69404368, 0.08333376, 0.09224351],
       [0.04675529, 0.84086369, 0.70699501, 0.42240727, 0.16169162],
       [0.45618527, 0.22140612, 0.58608982, 0.62555749, 0.98433767]])

In [19]:
np.random.randn(4,5)

array([[ 1.0202586 ,  0.28388841,  0.96774424, -0.69902996,  0.48258724],
       [ 0.65869543,  1.76075324, -0.78512232,  1.23090354, -0.3645538 ],
       [-0.70253652,  1.45919195,  0.19272573,  1.36951567, -0.427349  ],
       [-0.68464089,  1.91413646, -0.29463382, -0.65209727, -0.8153313 ]])

In [20]:
#generation of the equally spaced values with on actual array
np.linspace(0,23,5)

array([ 0.  ,  5.75, 11.5 , 17.25, 23.  ])

In [23]:
lsit_ofz_lists = [[],[],[]]
lsit_ofz_lists

[[], [], []]

In [26]:
lsit_ofz_lists = [[5, 6, 15],[12, 52, 223],[12, 25, 55]]
lsit_ofz_lists
np.array(lsit_ofz_lists)

array([[  5,   6,  15],
       [ 12,  52, 223],
       [ 12,  25,  55]])

In [29]:
#random generation from one number till the other
np.random.randint(19,2019)

1038

In [30]:
#random generation from one number till the other with certain steps
np.random.randint(10,29876,10)

array([22486, 22923,  3049, 23992,  3429, 18172, 24833, 10600, 12833,
        7229])

In [31]:
#taking the random value in other variable
random_array_001 = np.random.randint(10,5529,8)
random_array_001

array([ 772,  203,  132, 4524,  588,  692, 1430, 3597])

In [38]:
#min, max, argmax, variance, std deviation and argmin of the variables
random_array_002 = np.random.randint(2, 32, 6)
random_array_002

array([ 4, 25,  3,  8,  2, 23])

In [39]:
random_array_002.max()

25

In [40]:
random_array_002.min()

2

In [41]:
random_array_002.var()

90.47222222222221

In [42]:
random_array_002.std()

9.51168871558685

In [43]:
random_array_002.argmin()

4

In [44]:
random_array_002.argmax()

1

In [57]:
#reshapping the array
sample_test_array = np.random.randint(5, 44, 20)
sample_test_array

array([36,  8, 39, 42, 23, 31, 14, 32, 14, 20,  7, 27, 28,  9,  7, 25, 38,
       12, 21,  7])

In [58]:
#matrix shaped in other way
sample_test_array.shape

(20,)

In [63]:
sample_test_array.reshape(20,1)

array([[36],
       [ 8],
       [39],
       [42],
       [23],
       [31],
       [14],
       [32],
       [14],
       [20],
       [ 7],
       [27],
       [28],
       [ 9],
       [ 7],
       [25],
       [38],
       [12],
       [21],
       [ 7]])

In [64]:
#checking the datatype dtype
sample_test_array.dtype

dtype('int32')

In [78]:
liste = ([[3, 85, 9, 6],
          [8, 6, 62, 78], 
          [45, 6, 4, 843],
          [44, 56, 54, 8]])
sample_array_003 = np.array(liste)
sample_array_003

array([[  3,  85,   9,   6],
       [  8,   6,  62,  78],
       [ 45,   6,   4, 843],
       [ 44,  56,  54,   8]])

In [79]:
sample_array_003.T   #Transpose of a matrix np.array attribute is very essential to 
                     #convert a list into arrays and do the operation on them

array([[  3,   8,  45,  44],
       [ 85,   6,   6,  56],
       [  9,  62,   4,  54],
       [  6,  78, 843,   8]])

In [86]:
sample_array_003[3]  #array starts form index i.e the postion 0 to further

array([44, 56, 54,  8])

In [93]:
sample_array_003[1:3] 

array([[  8,   6,  62,  78],
       [ 45,   6,   4, 843]])

In [94]:
sample_array_003[1,2]

62

In [95]:
#Setting a fixed value 100 using index range (Broadcasting)
sample_array_003[1:2]=100
sample_array_003

array([[  3,  85,   9,   6],
       [100, 100, 100, 100],
       [ 45,   6,   4, 843],
       [ 44,  56,  54,   8]])

In [97]:
#set all values to certain
sample_array_003[:] = 20
sample_array_003

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [99]:
liste1 = ([[3, 45, 9, 6],
          [8, 6, 602, 7], 
          [45, 6, 24, 843],
          [33, 56, 54, 4]])
array_test12 = np.array(liste1)
array_test12

array([[  3,  45,   9,   6],
       [  8,   6, 602,   7],
       [ 45,   6,  24, 843],
       [ 33,  56,  54,   4]])

In [100]:
liste

[[3, 85, 9, 6], [8, 6, 62, 78], [45, 6, 4, 843], [44, 56, 54, 8]]

In [102]:
copy_test_array = array_test12.copy()
copy_test_array

array([[  3,  45,   9,   6],
       [  8,   6, 602,   7],
       [ 45,   6,  24, 843],
       [ 33,  56,  54,   4]])

In [103]:
array_test12[2][3]  #prints that position value

843

In [104]:
array_test12[2]  #prints row

array([ 45,   6,  24, 843])

In [105]:
array_test12 < 100  #checks in bool for true or false

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [106]:
#arithmetic operation on the array
sample_array_003 + array_test12

array([[ 23,  65,  29,  26],
       [ 28,  26, 622,  27],
       [ 65,  26,  44, 863],
       [ 53,  76,  74,  24]])

In [108]:
sample_array_003 - array_test12

array([[  17,  -25,   11,   14],
       [  12,   14, -582,   13],
       [ -25,   14,   -4, -823],
       [ -13,  -36,  -34,   16]])

In [109]:
sample_array_003/array_test12

array([[6.66666667, 0.44444444, 2.22222222, 3.33333333],
       [2.5       , 3.33333333, 0.03322259, 2.85714286],
       [0.44444444, 3.33333333, 0.83333333, 0.02372479],
       [0.60606061, 0.35714286, 0.37037037, 5.        ]])

In [111]:
array_number_001 = sample_array_003*array_test12
array_number_001

array([[   60,   900,   180,   120],
       [  160,   120, 12040,   140],
       [  900,   120,   480, 16860],
       [  660,  1120,  1080,    80]])

In [112]:
np.sqrt(array_number_001)       #square root

array([[  7.74596669,  30.        ,  13.41640786,  10.95445115],
       [ 12.64911064,  10.95445115, 109.72693379,  11.83215957],
       [ 30.        ,  10.95445115,  21.9089023 , 129.84606271],
       [ 25.69046516,  33.46640106,  32.86335345,   8.94427191]])

In [113]:
np.exp(array_number_001)        #exponential

array([[1.14200739e+026,             inf, 1.48938420e+078,
        1.30418088e+052],
       [3.06984964e+069, 1.30418088e+052,             inf,
        6.32743171e+060],
       [            inf, 1.30418088e+052, 2.89301918e+208,
                    inf],
       [4.30881707e+286,             inf,             inf,
        5.54062238e+034]])

In [114]:
np.sin(array_number_001)        #sine value

array([[-0.30481062,  0.99780327, -0.80115264,  0.58061118],
       [ 0.21942526,  0.58061118,  0.9881892 ,  0.98023966],
       [ 0.99780327,  0.58061118,  0.61601671,  0.80028587],
       [ 0.26243303,  0.99975317, -0.65021914, -0.99388865]])

In [116]:
array_number_001           #actual array doesnt change only changes when we take a copy of this in another memory

array([[   60,   900,   180,   120],
       [  160,   120, 12040,   140],
       [  900,   120,   480, 16860],
       [  660,  1120,  1080,    80]])

In [117]:
np.cos(array_number_001)

array([[-0.95241298,  0.0662467 , -0.59846007,  0.81418097],
       [-0.97562931,  0.81418097,  0.15323873, -0.19781357],
       [ 0.0662467 ,  0.81418097, -0.78773308, -0.59961865],
       [ 0.96495021, -0.02221717,  0.75974672, -0.11038724]])

In [118]:
np.tan(array_number_001)         #no cosec, cot and sec

array([[  0.32004039,  15.06193125,   1.33869021,   0.71312301],
       [ -0.22490638,   0.71312301,   6.44869097,  -4.95537106],
       [ 15.06193125,   0.71312301,  -0.78201199,  -1.33465806],
       [  0.27196536, -44.99912902,  -0.85583672,   9.00365495]])

In [123]:
np.log(array_number_001) 

array([[4.09434456, 6.80239476, 5.19295685, 4.78749174],
       [5.07517382, 4.78749174, 9.39598972, 4.94164242],
       [6.80239476, 4.78749174, 6.1737861 , 9.73269923],
       [6.49223984, 7.02108396, 6.98471632, 4.38202663]])

In [124]:
#Using the unique function
sports = np.array(['Golf', 'Cricket', 'Football', 'Football','Cricket','cricket','Basketball', 'Baseball'])

np.unique(sports)

array(['Baseball', 'Basketball', 'Cricket', 'Football', 'Golf', 'cricket'],
      dtype='<U10')

In [125]:
# in1d we can test values in one array - returns boolean output
np.in1d(['Fooseball','Cricket','Baseball'],sports)

array([False,  True,  True])

In [127]:
#Save array on hard disk in binary format (file extension is .npy)
np.save('array_number1', array_number_001)

In [128]:
np.savez('array_number12', a=array_number_001,b=array_test12)  #zip

In [129]:
np.load('array_number1.npy')

array([[   60,   900,   180,   120],
       [  160,   120, 12040,   140],
       [  900,   120,   480, 16860],
       [  660,  1120,  1080,    80]])

In [130]:
#Saving the arrays as text files

simple_array2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.savetxt('my_text.txt',simple_array2,delimiter=',')


In [131]:
simple_array2 = np.loadtxt('my_text.txt',delimiter = ',')

simple_array2

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.]])

In [132]:
#pandas import and check
labels = ['w','x','y','z']
list = [10,20,30,40]
array = np.array([10,20,30,40])
dict = {'w':10,'x':20,'y':30,'z':40}

In [133]:
pd.Series(data=list) #pandas series

0    10
1    20
2    30
3    40
dtype: int64

In [134]:
pd.Series(data=dict)

w    10
x    20
y    30
z    40
dtype: int64

In [135]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [140]:
sports1 = pd.Series([1,2,3,4,5],index = ['Cricket', 'Football','Basketball', 'Golf', 'pool'])
sports1

Cricket       1
Football      2
Basketball    3
Golf          4
pool          5
dtype: int64

In [143]:
sports1['pool']

5

In [145]:
sports1[4] #gives the pool reffered data as the index of that is 4

5

In [146]:
sports1[3] #gives the Golf reffered data as the index of that is 4

4

In [147]:
#series2
sports2 = pd.Series([1,2,3,4],index = ['Cricket', 'Football','Basketball', 'Golf'])
sports2

Cricket       1
Football      2
Basketball    3
Golf          4
dtype: int64

In [148]:
sports1 + sports2  #adding two series

Basketball    6.0
Cricket       2.0
Football      4.0
Golf          8.0
pool          NaN
dtype: float64

In [157]:
#dataframe for random generation need to import from numpy only random pd.Dataframe acts same as the np.array or np.matrix 
from numpy.random import randn
np.random.seed(1)
dataframe = pd.DataFrame(randn(10,6),index='A B C D E F G H I J'.split(),columns='Score1 Score2 Score3 Score4 Score5 Score6'.split())
dataframe

Score1    Score2    Score3    Score4    Score5    Score6
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408 -2.301539
B  1.744812 -0.761207  0.319039 -0.249370  1.462108 -2.060141
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.877858
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.502494
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.530355
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -0.012665
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.887629
H -0.747158  1.692455  0.050808 -0.636996  0.190915  2.100255
I  0.120159  0.617203  0.300170 -0.352250 -1.142518 -0.349343
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.885141

In [162]:
dataframe['Score1'] #only the index

A    1.624345
B    1.744812
C   -0.322417
D    0.042214
E    0.900856
F   -0.691661
G   -1.117310
H   -0.747158
I    0.120159
J   -0.208894
Name: Score1, dtype: float64

In [166]:
dataframe.loc['A'] #column

Score1    1.624345
Score2   -0.611756
Score3   -0.528172
Score4   -1.072969
Score5    0.865408
Score6   -2.301539
Name: A, dtype: float64

In [167]:
dataframe[['Score2','Score1']] #just some data needed

Score2    Score1
A -0.611756  1.624345
B -0.761207  1.744812
C -0.384054 -0.322417
D  0.582815  0.042214
E -0.683728  0.900856
F -0.396754 -0.691661
G  0.234416 -1.117310
H  1.692455 -0.747158
I  0.617203  0.120159
J  0.586623 -0.208894

In [168]:
type(dataframe['Score1']) #type

pandas.core.series.Series

In [171]:
dataframe['Score7'] = dataframe['Score1'] + dataframe['Score2']  #adding column
dataframe

Score1    Score2    Score3    Score4    Score5    Score6    Score7
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408 -2.301539  1.012589
B  1.744812 -0.761207  0.319039 -0.249370  1.462108 -2.060141  0.983605
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.877858 -0.706472
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.502494  0.625029
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.530355  0.217128
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -0.012665 -1.088414
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.887629 -0.882895
H -0.747158  1.692455  0.050808 -0.636996  0.190915  2.100255  0.945296
I  0.120159  0.617203  0.300170 -0.352250 -1.142518 -0.349343  0.737362
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.885141  0.377729

In [173]:
dataframe.drop('Score7',axis=1)  #deleting the column

Score1    Score2    Score3    Score4    Score5    Score6
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408 -2.301539
B  1.744812 -0.761207  0.319039 -0.249370  1.462108 -2.060141
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.877858
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.502494
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.530355
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -0.012665
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.887629
H -0.747158  1.692455  0.050808 -0.636996  0.190915  2.100255
I  0.120159  0.617203  0.300170 -0.352250 -1.142518 -0.349343
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.885141

In [175]:
dataframe  #original doesnt change

Score1    Score2    Score3    Score4    Score5    Score6    Score7
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408 -2.301539  1.012589
B  1.744812 -0.761207  0.319039 -0.249370  1.462108 -2.060141  0.983605
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.877858 -0.706472
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.502494  0.625029
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.530355  0.217128
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -0.012665 -1.088414
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.887629 -0.882895
H -0.747158  1.692455  0.050808 -0.636996  0.190915  2.100255  0.945296
I  0.120159  0.617203  0.300170 -0.352250 -1.142518 -0.349343  0.737362
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.885141  0.377729

In [176]:
# Use axis=0 for dropping rows and axis=1 for dropping columns
dataframe.drop('A',axis=0)

Score1    Score2    Score3    Score4    Score5    Score6    Score7
B  1.744812 -0.761207  0.319039 -0.249370  1.462108 -2.060141  0.983605
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.877858 -0.706472
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.502494  0.625029
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.530355  0.217128
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -0.012665 -1.088414
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.887629 -0.882895
H -0.747158  1.692455  0.050808 -0.636996  0.190915  2.100255  0.945296
I  0.120159  0.617203  0.300170 -0.352250 -1.142518 -0.349343  0.737362
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.885141  0.377729

In [177]:
dataframe.drop('Score6',axis=1,inplace=True)

In [178]:
dataframe   #removes actual column from the dataframe

Score1    Score2    Score3    Score4    Score5    Score7
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
B  1.744812 -0.761207  0.319039 -0.249370  1.462108  0.983605
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.706472
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.625029
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.217128
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.882895
H -0.747158  1.692455  0.050808 -0.636996  0.190915  0.945296
I  0.120159  0.617203  0.300170 -0.352250 -1.142518  0.737362
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.377729

In [179]:
dataframe.iloc[2] #location of the row

Score1   -0.322417
Score2   -0.384054
Score3    1.133769
Score4   -1.099891
Score5   -0.172428
Score7   -0.706472
Name: C, dtype: float64

In [180]:
dataframe.loc['D']['Score2']  #gives value of that row and column

0.5828152137158222

In [181]:
dataframe>0.5  #conditional

Score1  Score2  Score3  Score4  Score5  Score7
A    True   False   False   False    True    True
B    True   False   False   False    True    True
C   False   False    True   False   False   False
D   False    True   False    True    True    True
E    True   False   False   False   False   False
F   False   False   False   False   False   False
G   False   False    True    True   False   False
H   False    True   False   False   False    True
I   False    True   False   False   False    True
J   False    True    True    True   False   False

In [182]:
dataframe[dataframe>0.5]  #values greates than 0.5

Score1    Score2    Score3    Score4    Score5    Score7
A  1.624345       NaN       NaN       NaN  0.865408  1.012589
B  1.744812       NaN       NaN       NaN  1.462108  0.983605
C       NaN       NaN  1.133769       NaN       NaN       NaN
D       NaN  0.582815       NaN  1.144724  0.901591  0.625029
E  0.900856       NaN       NaN       NaN       NaN       NaN
F       NaN       NaN       NaN       NaN       NaN       NaN
G       NaN       NaN  1.659802  0.742044       NaN       NaN
H       NaN  1.692455       NaN       NaN       NaN  0.945296
I       NaN  0.617203       NaN       NaN       NaN  0.737362
J       NaN  0.586623  0.838983  0.931102       NaN       NaN

In [183]:
dataframe[dataframe['Score1']>0.5] #only for a one row

Score1    Score2    Score3    Score4    Score5    Score7
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
B  1.744812 -0.761207  0.319039 -0.249370  1.462108  0.983605
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.217128

In [185]:
dataframe[(dataframe['Score1']>0.1) & (dataframe['Score2'] > 0)] #more conditional statement

Score1    Score2   Score3   Score4    Score5    Score7
I  0.120159  0.617203  0.30017 -0.35225 -1.142518  0.737362

In [186]:
# Reset to default index value instead of A to J
dataframe.reset_index()

index    Score1    Score2    Score3    Score4    Score5    Score7
0     A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
1     B  1.744812 -0.761207  0.319039 -0.249370  1.462108  0.983605
2     C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.706472
3     D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.625029
4     E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.217128
5     F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
6     G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.882895
7     H -0.747158  1.692455  0.050808 -0.636996  0.190915  0.945296
8     I  0.120159  0.617203  0.300170 -0.352250 -1.142518  0.737362
9     J -0.208894  0.586623  0.838983  0.931102  0.285587  0.377729

In [188]:
# Setting new index value
newindex = 'IND JP CAN GE IT PL FY IU RT IP'.split()
dataframe['Countries'] = newindex
dataframe

Score1    Score2    Score3    Score4    Score5    Score7 Countries
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589       IND
B  1.744812 -0.761207  0.319039 -0.249370  1.462108  0.983605        JP
C -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.706472       CAN
D  0.042214  0.582815 -1.100619  1.144724  0.901591  0.625029        GE
E  0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.217128        IT
F -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414        PL
G -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.882895        FY
H -0.747158  1.692455  0.050808 -0.636996  0.190915  0.945296        IU
I  0.120159  0.617203  0.300170 -0.352250 -1.142518  0.737362        RT
J -0.208894  0.586623  0.838983  0.931102  0.285587  0.377729        IP

In [189]:
dataframe.set_index('Countries')

Score1    Score2    Score3    Score4    Score5    Score7
Countries                                                            
IND        1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
JP         1.744812 -0.761207  0.319039 -0.249370  1.462108  0.983605
CAN       -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.706472
GE         0.042214  0.582815 -1.100619  1.144724  0.901591  0.625029
IT         0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.217128
PL        -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
FY        -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.882895
IU        -0.747158  1.692455  0.050808 -0.636996  0.190915  0.945296
RT         0.120159  0.617203  0.300170 -0.352250 -1.142518  0.737362
IP        -0.208894  0.586623  0.838983  0.931102  0.285587  0.377729

In [190]:
dataframe.set_index('Countries',inplace=True) #actually making it true

In [191]:
dataframe

Score1    Score2    Score3    Score4    Score5    Score7
Countries                                                            
IND        1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
JP         1.744812 -0.761207  0.319039 -0.249370  1.462108  0.983605
CAN       -0.322417 -0.384054  1.133769 -1.099891 -0.172428 -0.706472
GE         0.042214  0.582815 -1.100619  1.144724  0.901591  0.625029
IT         0.900856 -0.683728 -0.122890 -0.935769 -0.267888  0.217128
PL        -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
FY        -1.117310  0.234416  1.659802  0.742044 -0.191836 -0.882895
IU        -0.747158  1.692455  0.050808 -0.636996  0.190915  0.945296
RT         0.120159  0.617203  0.300170 -0.352250 -1.142518  0.737362
IP        -0.208894  0.586623  0.838983  0.931102  0.285587  0.377729

In [193]:
#np.nan for not known values
dataframe = pd.DataFrame({'Cricket':[1,2,np.nan,4,6,7,2,np.nan],
                  'Baseball':[5,np.nan,np.nan,5,7,2,4,5],
                  'Tennis':[1,2,3,4,5,6,7,8],
                  'foozeball':[1,2,3,4,np.nan,6,7,8]})
dataframe

Cricket  Baseball  Tennis  foozeball
0      1.0       5.0       1        1.0
1      2.0       NaN       2        2.0
2      NaN       NaN       3        3.0
3      4.0       5.0       4        4.0
4      6.0       7.0       5        NaN
5      7.0       2.0       6        6.0
6      2.0       4.0       7        7.0
7      NaN       5.0       8        8.0

In [194]:
dataframe.dropna() #drops na values

Cricket  Baseball  Tennis  foozeball
0      1.0       5.0       1        1.0
3      4.0       5.0       4        4.0
5      7.0       2.0       6        6.0
6      2.0       4.0       7        7.0

In [196]:
dataframe.fillna(value = 0xAAFF)  #we can give values in any format

Cricket  Baseball  Tennis  foozeball
0      1.0       5.0       1        1.0
1      2.0   43775.0       2        2.0
2  43775.0   43775.0       3        3.0
3      4.0       5.0       4        4.0
4      6.0       7.0       5    43775.0
5      7.0       2.0       6        6.0
6      2.0       4.0       7        7.0
7  43775.0       5.0       8        8.0

In [197]:
dataframe.dropna(axis=1)

Tennis
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8

In [198]:
dataframe['Baseball'].fillna(value=dataframe['Baseball'].mean()) #creates and fills the value with the fillna with mean value

0    5.000000
1    4.666667
2    4.666667
3    5.000000
4    7.000000
5    2.000000
6    4.000000
7    5.000000
Name: Baseball, dtype: float64

In [200]:
# Create dataframe as given below
dat = {'CustID':['1001','1001','1002','1002','1003','1003'],
       'CustName':['UIPat','DatRob','Goog','Chrysler','Ford','GM'],
       'Profitinlakhs':[2005,3245,1245,8765,5463,3547]}
dataframe = pd.DataFrame(dat)
dataframe

CustID  CustName  Profitinlakhs
0   1001     UIPat           2005
1   1001    DatRob           3245
2   1002      Goog           1245
3   1002  Chrysler           8765
4   1003      Ford           5463
5   1003        GM           3547

In [204]:
CustID_grouped = dataframe.groupby("CustID")  #using groupby
CustID_grouped.mean()

Profitinlakhs
CustID               
1001             2625
1002             5005
1003             4505

In [205]:
dataframe.groupby('CustID').mean() 

Profitinlakhs
CustID               
1001             2625
1002             5005
1003             4505

In [206]:
CustID_grouped.std()

Profitinlakhs
CustID               
1001       876.812409
1002      5317.442995
1003      1354.816593

In [207]:
CustID_grouped.count()

CustName  Profitinlakhs
CustID                         
1001           2              2
1002           2              2
1003           2              2

In [208]:
CustID_grouped.max()

CustName  Profitinlakhs
CustID                        
1001      UIPat           3245
1002       Goog           8765
1003         GM           5463

In [209]:
CustID_grouped.min()

CustName  Profitinlakhs
CustID                         
1001      DatRob           2005
1002    Chrysler           1245
1003        Ford           3547

In [210]:
CustID_grouped.describe()  #describes the dataframe by above all parameters

Profitinlakhs                                                       \
               count    mean          std     min     25%     50%     75%   
CustID                                                                      
1001             2.0  2625.0   876.812409  2005.0  2315.0  2625.0  2935.0   
1002             2.0  5005.0  5317.442995  1245.0  3125.0  5005.0  6885.0   
1003             2.0  4505.0  1354.816593  3547.0  4026.0  4505.0  4984.0   

                
           max  
CustID          
1001    3245.0  
1002    8765.0  
1003    5463.0

In [211]:
CustID_grouped.describe().transpose()  #transpose of the dataframe

CustID                      1001         1002         1003
Profitinlakhs count     2.000000     2.000000     2.000000
              mean   2625.000000  5005.000000  4505.000000
              std     876.812409  5317.442995  1354.816593
              min    2005.000000  1245.000000  3547.000000
              25%    2315.000000  3125.000000  4026.000000
              50%    2625.000000  5005.000000  4505.000000
              75%    2935.000000  6885.000000  4984.000000
              max    3245.000000  8765.000000  5463.000000

In [212]:
CustID_grouped.describe().transpose()['1001'] #transpose with only one custID

Profitinlakhs  count       2.000000
               mean     2625.000000
               std       876.812409
               min      2005.000000
               25%      2315.000000
               50%      2625.000000
               75%      2935.000000
               max      3245.000000
Name: 1001, dtype: float64

In [214]:
dafa1 = pd.DataFrame({'CustID': ['101', '102', '103', '104'],
                        'Sales': [13456, 45321, 54385, 53212],
                        'Priority': ['CAT0', 'CAT1', 'CAT2', 'CAT3'],
                        'Prime': ['yes', 'no', 'no', 'yes']},
                        index=[0, 1, 2, 3])
dafa1

CustID  Sales Priority Prime
0    101  13456     CAT0   yes
1    102  45321     CAT1    no
2    103  54385     CAT2    no
3    104  53212     CAT3   yes

In [215]:
dafa2 = pd.DataFrame({'CustID': ['101', '103', '104', '105'],
                        'Sales': [13456, 54385, 53212, 4534],
                        'Payback': ['CAT4', 'CAT5', 'CAT6', 'CAT7'],
                        'Imp': ['yes', 'no', 'no', 'no']},
                         index=[4, 5, 6, 7]) 
dafa2

CustID  Sales Payback  Imp
4    101  13456    CAT4  yes
5    103  54385    CAT5   no
6    104  53212    CAT6   no
7    105   4534    CAT7   no

In [216]:
dafa3 = pd.DataFrame({'CustID': ['101', '104', '105', '106'],
                        'Sales': [13456, 53212, 4534, 3241],
                        'Pol': ['CAT8', 'CAT9', 'CAT10', 'CAT11'],
                        'Level': ['yes', 'no', 'no', 'yes']},
                        index=[8, 9, 10, 11])
dafa3

CustID  Sales    Pol Level
8     101  13456   CAT8   yes
9     104  53212   CAT9    no
10    105   4534  CAT10    no
11    106   3241  CAT11   yes

In [219]:
pd.concat([dafa1,dafa2],sort=True)   #concat both dataframes

CustID  Imp Payback Prime Priority  Sales
0    101  NaN     NaN   yes     CAT0  13456
1    102  NaN     NaN    no     CAT1  45321
2    103  NaN     NaN    no     CAT2  54385
3    104  NaN     NaN   yes     CAT3  53212
4    101  yes    CAT4   NaN      NaN  13456
5    103   no    CAT5   NaN      NaN  54385
6    104   no    CAT6   NaN      NaN  53212
7    105   no    CAT7   NaN      NaN   4534

In [218]:
pd.concat([dafa1,dafa2,dafa3],axis=1)

CustID    Sales Priority Prime CustID    Sales Payback  Imp CustID  \
0     101  13456.0     CAT0   yes    NaN      NaN     NaN  NaN    NaN   
1     102  45321.0     CAT1    no    NaN      NaN     NaN  NaN    NaN   
2     103  54385.0     CAT2    no    NaN      NaN     NaN  NaN    NaN   
3     104  53212.0     CAT3   yes    NaN      NaN     NaN  NaN    NaN   
4     NaN      NaN      NaN   NaN    101  13456.0    CAT4  yes    NaN   
5     NaN      NaN      NaN   NaN    103  54385.0    CAT5   no    NaN   
6     NaN      NaN      NaN   NaN    104  53212.0    CAT6   no    NaN   
7     NaN      NaN      NaN   NaN    105   4534.0    CAT7   no    NaN   
8     NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    101   
9     NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    104   
10    NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    105   
11    NaN      NaN      NaN   NaN    NaN      NaN     NaN  NaN    106   

      Sales    Pol Level  
0       NaN    NaN   NaN  
1       NaN    NaN   NaN  
2       NaN    NaN   NaN  
3       NaN    NaN   NaN  
4       NaN    NaN   NaN  
5       NaN    NaN   NaN  
6       NaN    NaN   NaN  
7       NaN    NaN   NaN  
8   13456.0   CAT8   yes  
9   53212.0   CAT9    no  
10   4534.0  CAT10    no  
11   3241.0  CAT11   yes

In [220]:
pd.merge(dafa1,dafa2,how='outer',on='CustID')  #index is Cust ID 

CustID  Sales_x Priority Prime  Sales_y Payback  Imp
0    101  13456.0     CAT0   yes  13456.0    CAT4  yes
1    102  45321.0     CAT1    no      NaN     NaN  NaN
2    103  54385.0     CAT2    no  54385.0    CAT5   no
3    104  53212.0     CAT3   yes  53212.0    CAT6   no
4    105      NaN      NaN   NaN   4534.0    CAT7   no

In [223]:
dataframe = pd.read_csv('games.csv')  #reading the file

In [224]:
dataframe.head()

id       type                                       name  \
0   12333  boardgame                          Twilight Struggle   
1  120677  boardgame                              Terra Mystica   
2  102794  boardgame                  Caverna: The Cave Farmers   
3   25613  boardgame  Through the Ages: A Story of Civilization   
4    3076  boardgame                                Puerto Rico   

   yearpublished  minplayers  maxplayers  playingtime  minplaytime  \
0         2005.0         2.0         2.0        180.0        180.0   
1         2012.0         2.0         5.0        150.0         60.0   
2         2013.0         1.0         7.0        210.0         30.0   
3         2006.0         2.0         4.0        240.0        240.0   
4         2002.0         2.0         5.0        150.0         90.0   

   maxplaytime  minage  users_rated  average_rating  bayes_average_rating  \
0        180.0    13.0        20113         8.33774               8.22186   
1        150.0    12.0        14383         8.28798               8.14232   
2        210.0    12.0         9262         8.28994               8.06886   
3        240.0    12.0        13294         8.20407               8.05804   
4        150.0    12.0        39883         8.14261               8.04524   

   total_owners  total_traders  total_wanters  total_wishers  total_comments  \
0         26647            372           1219           5865            5347   
1         16519            132           1586           6277            2526   
2         12230             99           1476           5600            1700   
3         14343            362           1084           5075            3378   
4         44362            795            861           5414            9173   

   total_weights  average_weight  
0           2562          3.4785  
1           1423          3.8939  
2            777          3.7761  
3           1642          4.1590  
4           5213          3.2943

In [225]:
pd.read_excel('pandas-Consumer.xlsx',sheet_name='Data1') #reading the excel sheet
#dataframe.to_excel('Consumer2.xlsx',sheet_name='Sheet1') and dataframe.to_csv('train2.csv',index=False) for importing

Income  HouseholdSize  AmountCharged
0       54              3           4016
1       30              2           3159
2       32              4           5100
3       50              5           4742
4       31              2           1864
5       55              2           4070
6       37              1           2731
7       40              2           3348
8       66              4           4764
9       51              3           4110
10      25              3           4208
11      48              4           4219
12      27              1           2477
13      33              2           2514
14      65              3           4214
15      63              4           4965
16      42              6           4412
17      21              2           2448
18      44              1           2995
19      37              5           4171
20      62              6           5678
21      21              3           3623
22      55              7           5301
23      42              2           3020
24      41              7           4828
25      54              6           5573
26      30              1           2583
27      48              2           3866
28      34              5           3586
29      67              4           5037
30      50              2           3605
31      67              5           5345
32      55              6           5370
33      52              2           3890
34      62              3           4705
35      64              2           4157
36      22              3           3579
37      29              4           3890
38      39              2           2972
39      35              1           3121
40      39              4           4183
41      54              3           3730
42      23              6           4127
43      27              2           2921
44      26              7           4603
45      61              2           4273
46      30              2           3067
47      22              4           3074
48      46              5           4820
49      66              4           5149

In [226]:
dafa1

CustID  Sales Priority Prime
0    101  13456     CAT0   yes
1    102  45321     CAT1    no
2    103  54385     CAT2    no
3    104  53212     CAT3   yes

In [227]:
dafa3

CustID  Sales    Pol Level
8     101  13456   CAT8   yes
9     104  53212   CAT9    no
10    105   4534  CAT10    no
11    106   3241  CAT11   yes

In [229]:
dafa1.join(dafa3, how='outer') #only with same attributes it gets joined

ValueError: columns overlap but no suffix specified: Index(['CustID', 'Sales'], dtype='object')

In [230]:
dataframe = pd.DataFrame({'custID':[1,2,3,4],'SaleType':['big','small','medium','big'],'SalesCode':['121','131','141','151']})
dataframe.head()

custID SaleType SalesCode
0       1      big       121
1       2    small       131
2       3   medium       141
3       4      big       151

In [231]:
dataframe['SaleType'].unique() #unique no repitition

array(['big', 'small', 'medium'], dtype=object)

In [232]:
dataframe['SaleType'].nunique() #number of unique

3

In [234]:
#Select from DataFrame using criteria from multiple columns
newdataframe = dataframe[(dataframe['custID']!=3) & (dataframe['SaleType']=='big')]
newdataframe

custID SaleType SalesCode
0       1      big       121
3       4      big       151

In [235]:
#defining function and apply the function later (user definition)
def profit(a):
    return a*4

In [236]:
dataframe['custID'].apply(profit)

0     4
1     8
2    12
3    16
Name: custID, dtype: int64

In [237]:
dataframe['SaleType'].apply(len)

0    3
1    5
2    6
3    3
Name: SaleType, dtype: int64

In [238]:
dataframe['custID'].sum() #sum of all entries in that column

10

In [239]:
del dataframe['custID'] #deleting permanantly not to be used more

In [240]:
dataframe

SaleType SalesCode
0      big       121
1    small       131
2   medium       141
3      big       151

In [241]:
dataframe.isnull()

SaleType  SalesCode
0     False      False
1     False      False
2     False      False
3     False      False

In [242]:
dataframe.dropna()

SaleType SalesCode
0      big       121
1    small       131
2   medium       141
3      big       151

In [243]:
dataframe.fillna('Not nan')

SaleType SalesCode
0      big       121
1    small       131
2   medium       141
3      big       151